include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    library_private_types_in_public_api: ignore
    deprecated_member_use: ignore
    unused_element: ignore
    unused_local_variable: ignore
